name: Instrumentality Build.

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    name: Build.
    runs-on: ubuntu-latest

    steps:
    - name: Git Checkout.
      uses: actions/checkout@v3

    - name: Rust Toolchain.
      uses: actions-rs/toolchain@v1
      with:
        toolchain: nightly
        override: true

    - name: Cargo Build for Release.
      uses: actions-rs/cargo@v1
      with:
        command: build
        args: --release