name: Instrumentality Test.

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    name: Test.
    runs-on: ubuntu-latest

    steps:
    - name: Git Checkout.
      uses: actions/checkout@v3

    - name: Start MongoDB.
      uses: supercharge/mongodb-github-action@1.9.0
      with:
        mongodb-version: '5.0'
        mongodb-replica-set: itest

    - name: Rust Toolchain.
      uses: actions-rs/toolchain@v1.0.6
      with:
        toolchain: stable
        override: true

    - name: Create TLS Certificates.
      run: |
          mkdir tls
          openssl req -x509 -newkey rsa:4096 -keyout tls/privkey.pem -out tls/cert.pem -days 365 -nodes -subj '/CN=localhost'

    - name: Create Config File.
      run: |
          cp InstrumentalityTestExample.toml InstrumentalityTest.toml

    - name: Test and Generate Coverage Report.
      run: |
          rustup component add llvm-tools-preview
          cargo install cargo-llvm-cov
          cargo llvm-cov > COVERAGE

    - name: Upload Coverage Report Artifact.
      uses: actions/upload-artifact@v3
      with:
        name: Coverage Report
        path: COVERAGE
